[package]
name = "localsecret"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.37", features = ["derive"] }
local-ip-address = "0.6.4"
rand = "0.9.1"
tokio = "1.44.2"
tower-http = { version = "0.6.2", features = ["fs"] }
